### ISSUE TITLE
error running task in queue

### ISSUE THREAD

**Issue by ovizii** [radarlog/docker-pritunl#2]
docker logs -f pritunl
shows these errors, any ideas?

```
[winter-plains-6752][2020-07-22 08:40:00,292][ERROR] Failed to create user cert requests
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/user/user.py", line 266, in initialize
    self.org.queue_com.popen(args)
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/queue/com.py", line 32, in popen
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
  user_id = "5f17fb609f6ba408097c2741"
  org_id  = "5f17fb609f6ba408097c273a"
[winter-plains-6752][2020-07-22 08:40:00,300][ERROR] Error running task in queue
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/queue/queue.py", line 224, in run
    self.task()
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/queues/dh_params.py", line 49, in task
    self.queue_com.popen(args)
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/queue/com.py", line 32, in popen
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
  queue_type = "dh_params"
  queue_id   = "5f17fb609f6ba408097c273d"
[winter-plains-6752][2020-07-22 08:40:00,300][ERROR] Error running task in queue
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/queue/queue.py", line 224, in run
    self.task()
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/queues/init_org_pooled.py", line 30, in task
    self.org.initialize(queue_user_init=False)
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/organization/organization.py", line 117, in initialize
    ca_user.initialize()
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/user/user.py", line 266, in initialize
    self.org.queue_com.popen(args)
  File "/usr/lib/python2.7/site-packages/pritunl-1.29.2276.91-py2.7.egg/pritunl/queue/com.py", line 32, in popen
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
  queue_type = "init_org_pooled"

```

**Comment by radarlog** [comment]
sorry, no idea, I have the same, probably related to the upstream version
